[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]

# Fuzz testing configuration
[fuzz]
runs = 256
max_test_rejects = 65536

# Invariant testing configuration
[invariant]
runs = 256
depth = 64
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
